name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Specify Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier:fix

      - name: Run Linter
        run: npm run lint # Adjust this command based on your linter setup

  deploy:
    runs-on: ubuntu-latest
    needs: lint # Ensure this job runs after the lint job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Specify Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Set this in your GitHub secrets
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Set this in your GitHub secrets
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Set this in your GitHub secrets
        run: npx vercel --prod --confirm --token $VERCEL_TOKEN